#!/bin/sh

# chmod +x shetup

echo 'Show all files in finder...'
defaults write com.apple.finder AppleShowAllFiles YES

echo 'Show all extensions in finder...'
defaults write NSGlobalDomain AppleShowAllExtensions YES

echo 'Show file path in finder...'
defaults write com.apple.finder _FXShowPosixPathInTitle YES

echo 'restart finder...'
killall Finder

echo 'Set subl sym link...'
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

echo 'fetch git completion bash file...'
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash > ~/.git-completion.bash
